
<img align="left" width="75" height="75"  src="https://upload.wikimedia.org/wikipedia/en/e/e4/National_University_of_Computer_and_Emerging_Sciences_logo.png"> 

<h1 align="center" style="color:Brown;"> Machine Learning FFANN </h1> <h3 align="center" style="color:DarkRed;">  <h3><div align="right" style="color:Purple;"> </div></h3></h3> 

---

    


In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler


In [117]:
data=pd.read_csv("Iris.csv",header=0)
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [118]:

## Data pre-processing
df2 = data.loc[:,['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm','Species']]
feat = df2.iloc[:,:-1].values
label = df2.iloc[:,-1:].values

#Encoding Categorical Variable Species
from sklearn.preprocessing import LabelEncoder
LE1 = LabelEncoder()
label = np.array(LE1.fit_transform(label[:,-1]))
Label = pd.get_dummies(label).values
        
#spliting data into test and train set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(feat,Label,test_size=30)

#Normalising the inputs
sc = StandardScaler()
sc.fit(x_train)
X_train=sc.transform(x_train)
X_test = sc.transform(x_test)


In [119]:
error = []
class FeedForwardANN:

    ## Class inatialization 
    def __init__(self,inputlayer,hiddenlayer,outputlayer):
        np.random.seed(1)
        self.numb_of_Iperceptron = inputlayer
        self.numb_of_Hperceptron = hiddenlayer[0]
        self.numb_of_Operceptron = outputlayer
        self.numb_of_Hlayer = hiddenlayer[1]
        self.W1 = np.random.randn(inputlayer,16)
        self.W2 = np.random.randn(16,outputlayer)
        self.B1 = np.zeros((1,16))
        self.B2 = np.zeros((1,outputlayer))

    ## Activation function
    def sigmoid(self, X):
        return 1.0/(1.0 + np.exp(-X))
    
    ## Forward Propogate
    def forward_propagate(self,X):
        y_hat =[]
        self.Z1 = np.matmul(X,self.W1) + self.B1
        self.A1 = self.sigmoid(self.Z1)
        self.Z2 = np.matmul(self.A1, self.W2) + self.B2
        self.A2 = self.sigmoid(self.Z2) 
        y_hat.append(self.A2)
        return y_hat
    
    ## Trainig based on Forward Propogate    
    def train(self, inputs, targets, epochs, learning_rate):
        for i in range(epochs):
            sum_errors = 0
            # iterate through all the training data
            for j, input in enumerate(inputs):
                target = targets[j]
                # activate the network!
                output = self.forward_propagate(input)
                error.append(np.subtract(target, output))
                # tracking of the MSE
                sum_errors += self._mse(target, output)
        
        print('\n\nMean Square Error is : {} \n'.format(sum_errors))
        
    
    ## Error/Cost function
    def _mse(self, target, output):
        return np.average((target - output) ** 2)
        


In [120]:
#pred = []
FFANN = FeedForwardANN(len(df2.columns)-1,[16,1],3)#len(np.unique(label)))
FFANN.train(X_train, Label, 50, 0.2)
pred = FFANN.forward_propagate(X_test)
print('Predicted outcome on test data in %age form of each perceptron in Output Layer \n\n {} '.format(pred[0]*100))



Mean Square Error is : 43.97812338696865 

Predicted outcome on test data in %age form of each perceptron in Output Layer 

 [[82.43405402 79.0069015  47.6712108 ]
 [90.84463936 24.09507642 86.86804162]
 [80.7701501  79.90624925 33.48863806]
 [86.54854466 52.40941483 79.2939006 ]
 [89.04978484 34.63721903 72.60231012]
 [82.31934998 78.40497227 43.14459615]
 [91.96949461 12.6703995  82.13653671]
 [81.32458627 79.43654269 19.58721038]
 [90.64278301 26.2781325  78.84189661]
 [90.1774125  28.64363144 47.20237966]
 [87.24112599 42.47747139 42.94904319]
 [91.99514431 21.54697297 76.78830138]
 [91.23141379 35.73969289 66.06160982]
 [91.88669292 15.21630386 80.62157659]
 [90.63232872 27.89300453 66.62184069]
 [81.24296121 81.99138674 23.56212051]
 [86.39186329 52.63214112 71.74950383]
 [87.03934017 53.80770925 73.95255016]
 [88.67685    39.78793121 48.68343987]
 [83.43016852 86.05887372 14.96282616]
 [90.03294496 32.29083684 76.13721232]
 [90.77434371 29.54370946 73.21364701]
 [87.88342921 3

In [121]:
predict =[]
for i in range(len(pred[0])):
    max = np.max(pred[0][i])
    if (max == pred[0][i][0]):
        predict.append('Iris-virginicia')
    if (max == pred[0][i][1]):
        predict.append('Iris-Setosa')
    if (max == pred[0][i][2]):
        predict.append('Iris-versicolor')

In [122]:
actual = []
for i in range(len(y_test)):
    maxact = np.max(y_test[i])
    if (maxact == y_test[i][0]):
        actual.append('Iris-Setosa')
    if (maxact == y_test[i][1]):
        actual.append('Iris-versicolor')
    if (maxact == y_test[i][2]):
        actual.append('Iris-virginica')


In [123]:
predicted_Label = pd.DataFrame(np.array(predict),columns=['Predicted Label'])
actual_Label = pd.DataFrame(np.array(actual),columns=['Actual Label'])
feat_col = pd.DataFrame(data=x_test,columns=['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm'])

Final = pd.concat([feat_col,actual_Label,predicted_Label],axis='columns')

In [124]:
Final

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm     Actual Label  \
0             5.8           4.0            1.2           0.2      Iris-Setosa   
1             7.7           2.6            6.9           2.3   Iris-virginica   
2             5.4           3.7            1.5           0.2      Iris-Setosa   
3             7.0           3.2            4.7           1.4  Iris-versicolor   
4             6.3           3.3            4.7           1.6  Iris-versicolor   
5             5.7           3.8            1.7           0.3      Iris-Setosa   
6             6.3           3.3            6.0           2.5   Iris-virginica   
7             4.8           3.4            1.6           0.2      Iris-Setosa   
8             6.5           3.2            5.1           2.0   Iris-virginica   
9             5.4           3.0            4.5           1.5  Iris-versicolor   
10            5.5           2.6            4.4           1.2  Iris-versicolor   
11            6.4           2.8            5.6           2.2   Iris-virginica   
12            6.3           2.5            5.0           1.9   Iris-virginica   
13            6.3           3.4            5.6           2.4   Iris-virginica   
14            6.0           3.0            4.8           1.8   Iris-virginica   
15            5.1           3.5            1.4           0.2      Iris-Setosa   
16            6.6           2.9            4.6           1.3  Iris-versicolor   
17            6.7           3.1            4.4           1.4  Iris-versicolor   
18            5.6           3.0            4.1           1.3  Iris-versicolor   
19            4.9           3.0            1.4           0.2      Iris-Setosa   
20            6.7           2.5            5.8           1.8   Iris-virginica   
21            6.4           2.7            5.3           1.9   Iris-virginica   
22            6.1           3.0            4.6           1.4  Iris-versicolor   
23            5.4           3.4            1.7           0.2      Iris-Setosa   
24            5.6           2.7            4.2           1.3  Iris-versicolor   
25            6.1           2.8            4.7           1.2  Iris-versicolor   
26            6.0           2.7            5.1           1.6  Iris-versicolor   
27            5.5           4.2            1.4           0.2      Iris-Setosa   
28            5.2           2.7            3.9           1.4  Iris-versicolor   
29            4.8           3.4            1.9           0.2      Iris-Setosa   

    Predicted Label  
0   Iris-virginicia  
1   Iris-virginicia  
2   Iris-virginicia  
3   Iris-virginicia  
4   Iris-virginicia  
5   Iris-virginicia  
6   Iris-virginicia  
7   Iris-virginicia  
8   Iris-virginicia  
9   Iris-virginicia  
10  Iris-virginicia  
11  Iris-virginicia  
12  Iris-virginicia  
13  Iris-virginicia  
14  Iris-virginicia  
15      Iris-Setosa  
16  Iris-virginicia  
17  Iris-virginicia  
18  Iris-virginicia  
19      Iris-Setosa  
20  Iris-virginicia  
21  Iris-virginicia  
22  Iris-virginicia  
23      Iris-Setosa  
24  Iris-virginicia  
25  Iris-virginicia  
26  Iris-virginicia  
27  Iris-virginicia  
28  Iris-virginicia  
29  Iris-virginicia

## MODEL EVALUATION ON MNIST DATASET

In [88]:
mnist = pd.read_csv('mnist.csv')

In [89]:
mnist.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      4    0    0    0    0    0    0    0    0    0  ...      0      0   
3      1    0    0    0    0    0    0    0    0    0  ...      0      0   
4      9    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [106]:
## Data pre-processing
feat = mnist.iloc[:,1:].values
label = mnist.iloc[:,0:1].values


In [107]:
#Encoding Categorical Variable Species
from sklearn.preprocessing import LabelEncoder
LE1 = LabelEncoder()
label = np.array(LE1.fit_transform(label[:,-1]))
Label = pd.get_dummies(label).values
        
#spliting data into test and train set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(feat,Label,test_size=30)

#Normalising the inputs
#sc = StandardScaler()
#sc.fit(x_train)
#X_train=sc.transform(x_train)
#X_test = sc.transform(x_test)


In [103]:
#pred = []
FFANN = FeedForwardANN(len(mnist.columns)-1,[16,1],len(np.unique(label)))
FFANN.train(x_train, Label, 50, 0.2)
pred = FFANN.forward_propagate(x_test)
#print('Predicted outcome on test data, of each perceptron in Output Layer \n\n {} '.format(pred))

C:\Users\RAPTOR\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:18: RuntimeWarning: overflow encountered in exp




Mean Square Error is : 24516.35904751916 



## Conclusion

Our model didnt not gave result near to any accuaray and completly failed the predicted outcomes with the mean square error of very large value, when the number of perceptrons in hidden layers are 16. Maybe it will give better results on increasing the hidden layers and number of perceptrons in each layer.

In [116]:
print('Predicted outcome in %age form of each perceptron in Output Layer is \n\n {} '.format(pred[0]*100))

Predicted outcome in %age form of each perceptron in Output Layer is 

 [[39.1929935  28.15324436 11.05363905 60.27991878 56.60665906 93.56906745
  30.79561788 82.27871608 27.53939616 93.98709199]
 [51.26401712 93.91617505 38.49164682 48.82665193 11.21821458 86.19038437
   6.30134539 80.63615676 72.37169717 94.06650867]
 [72.38433555 37.06765673  5.19553948 85.39310136 37.39292154 85.98110432
   1.38111653 89.94477695 90.53299027 97.82285245]
 [51.30805512 63.53109595 73.28146696 31.29022292 16.74377582 56.60819676
   4.90439629 50.53226618 58.15753391 98.43375677]
 [ 1.81206847  8.31778491  3.82242993 94.69180056 23.79897988 89.64367045
  28.20647904 94.4491751  52.01465684 68.87759191]
 [77.14875714 54.24713921 52.55451788 75.2983812  25.70472487 69.14115532
   1.66320829 89.33201765 80.74519436 92.55644826]
 [26.25257031 86.0565812   9.95687469 49.03066105  7.18411148 82.43337858
  43.24675298 83.22356507 65.7318538  76.16240447]
 [73.68271247 63.68881606  5.83713217 68.8004372   4.